config/routes.rb
Rails.application.routes.draw do

  post 'wechat_donate/create'

  post 'wechat_donate/notify'

  get 'wechat_donate/form_list', as: 'wechat_form_list'

  resources :item_categories

  resources :undetermined_funds

  namespace :region do
    get 'country', as: :country
    get 'state', as: :state
    get 'city', as: :city
  end

  namespace :schoolfellow do
    resources :teach_experiences
  end

  resources :teacher_titles

  resources :majors

  resources :degrees

  get 'users/search'
  post 'users/search', to:'users#do_search', as: 'user_search'

  nested_actions = [:new, :create]
  origin_actions = [:show, :edit, :update, :destroy]

  resources :customer_groups

  resources :donation_types

  resources :univ_units

  resources :univ_unit_managers

  resources :usage_types

  resources :projects do
    resources :donation_records, only: nested_actions
    resources :item_donation_records, only: nested_actions
    resources :usage_records, only: nested_actions
    scope module: :project do
      resources :link_men
      resources :news, only: nested_actions
      resources :necessary_dates, only: nested_actions
    end
    member do
      get 'history', as: :history
      get 'new_attachment'
      post 'attachments', to: 'projects#create_attachment', as: :attachments
      delete 'attachments/:attachment_id', to: 'projects#destroy_attachment', as: :attachment
    end
  end

    
  namespace :project do
    resources :news, only: origin_actions
    resources :necessary_dates, only: origin_actions
  end

  get 'link_men/search'
  post 'link_men/search', to: 'link_men#search', as: 'link_man_search'
  
  get 'customers/search', to: 'customers#search', as: 'customer_search'
  post 'customers/search', to: 'customers#do_search'

  resources :usage_records, only: origin_actions do
    member do
      get 'new_attachment'
      post 'attachments', to: 'usage_records#create_attachment', as: :attachments
      delete 'attachments/:attachment_id', to: 'usage_records#destroy_attachment', as: :attachment
    end
  end

  resources :donation_records, only: origin_actions do
    member do
      get 'trans_undetermined_in', as: :trans_undetermined_in
      post 'trans_undetermined_in', to: 'donation_records#handle_undetermined_trans'
      get 'new_attachment'
      post 'attachments', to: 'donation_records#create_attachment', as: :attachments
      delete 'attachments/:attachment_id', to: 'donation_records#destroy_attachment', as: :attachment
    end
  end

  resources :items, only: origin_actions
  resources :item_donation_records, only: origin_actions do
    resources :items, only: nested_actions
    member do
      get 'new_attachment'
      post 'attachments', to: 'item_donation_records#create_attachment', as: :attachments
      delete 'attachments/:attachment_id', to: 'item_donation_records#destroy_attachment', as: :attachment
    end
  end

  scope shallow_prefix: :donation_record do
    resources :donation_record do
      resources :actual_funds, controller: 'donation_record/actual_funds', shallow: true
      resources :interest_periods, controller: 'donation_record/interest_periods', shallow: true
    end
  end

  namespace :usage_record do
    resources :funds, only: [:show, :update, :edit]
  end
  resources :usage_records do
    resources :funds, controller: 'usage_record/funds', only: nested_actions
  end
  resources :individual_customers do
    resources :study_experiences, controller: 'schoolfellow/study_experiences'
    resources :teach_experiences, controller: 'schoolfellow/teach_experiences'
  end

  resources :fund_types

  resources :funds

  resources :project_types

  resources :project_states

  resources :project_levels

  resources :projects

  resources :customers do
    get 'edit_type', as: :edit_type
    post 'type_change', as: :type_change
    resources :contact_records
  end

  get 'common_customer/check_input', as: :common_customer_check_input, to: 'common_customers#check_input'

  resources :customer_groups do
    delete "customers/:id", to: 'customer_groups#delete_customer', as: :customer
    get "customers/:id", to: 'customer_groups#delete_customer'
  end
  resources :online_customers

  resources :corporate_customers do
    resources :link_men, controller: 'corporate_customers/link_men'
  end

  resources :individual_customers do
    resources :univ_experiences, controller: :schoolfellows
  end

  resources :customers

  namespace :employee do
    get 'manage', to: 'manage#index'
    get 'search', as: :search, to: 'manage#search'
    post 'search', as: :get_search, to: 'manage#result'
    namespace :manage do
      get 'projects'
      get 'customers'
      get 'funds', as: :funds
      namespace :fund do
        get 'manage_unit', as: :manage_unit
        get 'undetermined_fund', as: :undetermined_fund
      end
      get 'others'
    end
  end

  resources :employees

  devise_for :users, skip: [:registrations], controllers: { sessions: "users/sessions" } , path_names: { sign_in: 'login', sign_out: 'logout' }

  devise_scope :user do
    get "login", to: "users/sessions#new", as: :login
    delete "logout", to: "users/sessions#destroy", as: :logout
  end
  
  resources :users, only: [:show], :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ } #don't set this before devise, which will be confused between /:id <=> /sign_up

  root to: 'main#index'
  
  get 'main/index'

end

app/models/individual_customer.rb
class IndividualCustomer < ActiveRecord::Base
  include CommonCustomer
  acts_as_common_customer

  has_one :schoolfellow, dependent: :destroy, validate: true
  belongs_to :corporate, class_name: "CorporateCustomer", foreign_key: :corporate_customer_id
  has_many :corporate_customer_link_men, class_name: 'CorporateCustomer::LinkMan', dependent: :destroy
  has_many :corporates, class_name: :CorporateCustomer, through: :corporate_customer_link_men, source: :corporate_customer

  def gender_t
    gender ? '男' : '女'
  end
end

app/controllers/individual_customers_controller.rb
class IndividualCustomersController < CommonCustomersController
  before_action :set_school_fellow
  before_action :set_experiences
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experiences
      @study_experiences = @schoolfellow ? @schoolfellow.study_experiences.order(:attendance_date) : []
      @teach_experiences = @schoolfellow ? @schoolfellow.teach_experiences.order(:teach_start) : []
    end
    def set_school_fellow
      @schoolfellow = @self_customer ?  @self_customer.schoolfellow : nil 
    end
    def self_params
      sp = super
      sp.merge! params.require(@SelfType).permit(:gender, :nation, :native_place, :birthday,
        :corporate_customer_id, :title)
      sp
    end
end

app/helpers/individual_customers_helper.rb
module IndividualCustomersHelper
  def lkt(*args)
    t(*args, scope: 'helpers.link.individual_customer')
  end
  def default_gender
    return 1 if @self_customer.gender.nil?
    @self_customer.gender ? 1 : 0
  end
end

app/views/individual_customers/_form.html.erb
<div class="common-form">
<%= form_for(@self_customer) do |f| %>
  <% if @self_customer.errors.any? %>
    <div id="error_explanation">
      <%= error_messages_for @self_customer %>
    </div>
  <% end %>

  <%= f.fields_for :customer do |c_f| %>
    <%= render 'customers/form', {f: c_f, of: f} %>
  <% end %>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.select :gender, options_for_select({'男'=>1,'女'=>0}, default_gender)%>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday, start_year: 1900 , include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :nation %><br>
    <%= f.text_field :nation %>
  </div>
  <div class="field">
    <%= f.label :native_place %><br>
    <%= f.text_field :native_place %>
  </div>
  <div class="field">
    <%= f.label :corporate %><%= link_to "添加公司", new_corporate_customer_path, target: :_blank %><br>
    <%= f.select :corporate_customer_id, CorporateCustomer.all_spy.collect{ |e| [e.name_with_py!, e.id] }, { include_blank: true }%>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit '提交'%>
  </div>
<% end %>
</div>

app/views/individual_customers/_info.html.erb
<div id="project-info">
  <div class="info-block">
    <p>
      <div><strong>姓名：</strong> <span><%= @self_customer.customer.name %></span></div>
      <div><strong>性别：</strong> <span><%= "空" %></span></div>
      <div><strong>民族：</strong> <span><%= "空" %></span></div>
      <div><strong>出生日期：</strong> <span><%= "空" %></span></div>
      <div><strong>籍贯：</strong> <span><%= "空" %></span></div>
      <div><strong>现居地：</strong> <span><%= "空" %></span></div>
    </p>
    <p>
      <div><strong>电话：</strong> <span><%= "空" %></span></div>
      <div><strong>邮箱：</strong> <span><%= "空" %></span></div>
      <div><strong>传真：</strong> <span><%= "空" %></span></div>
      <div><strong>邮编：</strong> <span><%= "空" %></span></div>
    </p>
    <p>
      <div><strong>联系人：</strong> <span><%= "空" %></span></div>
      <div><strong>电话：</strong> <span><%= "空" %></span></div>
      <div><strong>邮箱：</strong> <span><%= "空" %></span></div>
      <div><strong>传真：</strong> <span><%= "空" %></span></div>
      <div><strong>邮编：</strong> <span><%= "空" %></span></div>
    </p>
  </div>
  <hr>
  <div class="info-block">
    <p>
      <div><strong>校友信息：</strong> <span>数学研究所</span></div>
    </p>
  </div>
  <hr>
  <div class="info-block">
    <p>
      <div><strong>来往记录：</strong> <span><%= "空" %></span></div>
    </p>
  </div>
</div>

app/views/individual_customers/_show.html.erb
<div class="info-show">
  <div class="info-block">
    <p>
      <div><strong><%= @self_customer.class.human_attribute_name :name %>：</strong> <span><%= @self_customer.name! %></span></div>
      <div><small>创建者： <span><%= link_to current_people.name, current_user %></span></small></div>
    </p>
    <p>
      <div><strong>性别：</strong> <span><%= @self_customer.gender_t %></span></div>
      <div><strong>生日：</strong> <span><%= @self_customer.birthday %></span></div>
      <div><strong>民族：</strong> <span><%= @self_customer.nation %></span></div>
      <div><strong>籍贯：</strong> <span><%= @self_customer.address! %></span></div>
      <div><strong>公司（单位）：</strong> <span><%= link_to(@self_customer.corporate.name!, @self_customer.corporate) if @self_customer.corporate %></span></div>
      <div><strong>职位（头衔）：</strong> <span><%= @self_customer.title %></span></div>
    </p>
  </div>
</div>
<%= link_to '查看更多信息', @self_customer %>



<%# if @current_user.nil? %>
  <%#= link_to '编辑', edit_project_path(@project) %> 
  <%#= link_to '返回', projects_path %>
<%# end %>

app/views/individual_customers/edit.html.erb
<%= content_for :nav_bar_title do %>
  客户信息编辑
<% end %>
<%= content_for :nav_bar_function_area do %>
  <% if current_user.user_type.downcase == :employee.to_s %>
    <%= link_to '返回', individual_customer_path(@self_customer.id) %>
  <% end %>
<% end %>

<%= render 'form' %>
<%= link_to '变更用户类型', customer_edit_type_path(@self_customer.customer) %>

app/views/individual_customers/index.html.erb
<h1>个人客户列表</h1>

<table>
  <thead>
    <tr>
      <th>姓名</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @self_customers.each do |individual_customer| %>
      <tr>
        <td><%= individual_customer.customer %></td>
        <td><%= link_to '显示', individual_customer %></td>
        <td><%= link_to '编辑', edit_individual_customer_path(individual_customer) %></td>
        <td><%= link_to '删除', individual_customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新建个人客户', new_individual_customer_path %>

app/views/individual_customers/new.html.erb
<%= render 'individual_customers/form' %>

app/views/individual_customers/show.html.erb
<%= content_for :nav_bar_function_area do %>
  <% if current_user.user_type.downcase == :employee.to_s %>
    <%= link_to '编辑', edit_individual_customer_path(@self_customer) %> |
    <%= link_to '返回', employee_manage_customers_path %> 
    <% if current_user.account.to_s == 'fkadmin' %>
      |<%= link_to '删除', individual_customer_path(@self_customer), method: :delete, data: { confirm: t('helpers.link.delete.individual_customer.confirm') } %>
    <% end %>
  <% end %>
<% end %>

<%= content_for :nav_bar_title do %>
    客户信息
<% end %>

<div class="info-show">
  <div class="info-block">
    <p>
      <div><strong><%= @self_customer.class.human_attribute_name :name %>：</strong> <span><%= @self_customer.name! %></span></div>
      <div><small>录入人： <span><%= link_to @self_customer.creator!.name, @self_customer.creator! %></span></small></div>
    </p>
    <p>
      <div><strong>性别：</strong> <span><%= @self_customer.gender_t %></span></div>
      <div><strong>生日：</strong> <span><%= @self_customer.birthday %></span></div>
      <div><strong>民族：</strong> <span><%= @self_customer.nation %></span></div>
      <div><strong>籍贯：</strong> <span><%= @self_customer.address! %></span></div>
      <div><strong>公司（单位）：</strong> <span><%= link_to(@self_customer.corporate.name!, @self_customer.corporate) if @self_customer.corporate %></span></div>
      <div><strong>职位（头衔）：</strong> <span><%= @self_customer.title %></span></div>
    </p>
  </div>
</div>
<div id="project-info">
  <%= render 'common_customers/info' %>
  <hr>
  <%= render 'common_customers/record' %>
  <div class="info-show">
    <p>
      <strong>校友信息：</strong><%= link_to lkt('new_study_experience'), new_individual_customer_study_experience_path(@self_customer) %>
      |<%= link_to lkt('new_teach_experience'), new_individual_customer_teach_experience_path(@self_customer) %>
      <div class="info-block">    
      <% @study_experiences.each do |e| %>
      <p>
        <div><strong>学历：</strong> <span><%= e.degree.name %></span></div>
        <div><strong>学号：</strong> <span><%= e.student_number %></span></div>
        <div><strong>入学时间：</strong> <span><%= l e.attendance_date, format: :long %></span></div>
        <div><strong>毕业时间：</strong> <span><%= l e.graduated_date, format: :long %></span></div>
        <div><strong>学院：</strong> <span><%= e.college.name %></span></div>
        <div><strong>专业：</strong> <span><%= e.major.name %></span></div>
        <%= link_to '删除', individual_customer_study_experience_path(@self_customer, e), method: :delete, data: { confirm: t('helpers.link.delete.confirm') } %>
      </p>
      <% end %>
      <% @teach_experiences.each do |e| %>
      <p>
        <div><strong>职工号：</strong> <span><%= e.idnum %></span></div>
        <div><strong>任教时间：</strong> <span><%= l e.teach_start, format: :long %></span>—
          <span><%= l e.teach_end, format: :long %></span></div>
        <div><strong>学院：</strong> <span><%= e.college.name %></span></div>
        <div><strong>职位：</strong> <span><%= e.title %></span></div>
        <%= link_to '删除', individual_customer_teach_experience_path(@self_customer, e), method: :delete, data: { confirm: t('helpers.link.delete.confirm') } %>
      </p>
      <% end %>
      </div>
    </p>
  </div>
</div>


<%# if @current_user.nil? %>
  <%#= link_to '编辑', edit_project_path(@project) %> 
  <%#= link_to '返回', projects_path %>
<%# end %>