config/routes.rb
Rails.application.routes.draw do

  post 'wechat_donate/create'

  post 'wechat_donate/notify'

  get 'wechat_donate/form_list', as: 'wechat_form_list'

  resources :item_categories

  resources :undetermined_funds

  namespace :region do
    get 'country', as: :country
    get 'state', as: :state
    get 'city', as: :city
  end

  namespace :schoolfellow do
    resources :teach_experiences
  end

  resources :teacher_titles

  resources :majors

  resources :degrees

  get 'users/search'
  post 'users/search', to:'users#do_search', as: 'user_search'

  nested_actions = [:new, :create]
  origin_actions = [:show, :edit, :update, :destroy]

  resources :customer_groups

  resources :donation_types

  resources :univ_units

  resources :univ_unit_managers

  resources :usage_types

  resources :projects do
    resources :donation_records, only: nested_actions
    resources :item_donation_records, only: nested_actions
    resources :usage_records, only: nested_actions
    scope module: :project do
      resources :link_men
      resources :news, only: nested_actions
      resources :necessary_dates, only: nested_actions
    end
    member do
      get 'history', as: :history
      get 'new_attachment'
      post 'attachments', to: 'projects#create_attachment', as: :attachments
      delete 'attachments/:attachment_id', to: 'projects#destroy_attachment', as: :attachment
    end
  end

    
  namespace :project do
    resources :news, only: origin_actions
    resources :necessary_dates, only: origin_actions
  end

  get 'link_men/search'
  post 'link_men/search', to: 'link_men#search', as: 'link_man_search'
  
  get 'customers/search', to: 'customers#search', as: 'customer_search'
  post 'customers/search', to: 'customers#do_search'

  resources :usage_records, only: origin_actions do
    member do
      get 'new_attachment'
      post 'attachments', to: 'usage_records#create_attachment', as: :attachments
      delete 'attachments/:attachment_id', to: 'usage_records#destroy_attachment', as: :attachment
    end
  end

  resources :donation_records, only: origin_actions do
    member do
      get 'trans_undetermined_in', as: :trans_undetermined_in
      post 'trans_undetermined_in', to: 'donation_records#handle_undetermined_trans'
      get 'new_attachment'
      post 'attachments', to: 'donation_records#create_attachment', as: :attachments
      delete 'attachments/:attachment_id', to: 'donation_records#destroy_attachment', as: :attachment
    end
  end

  resources :items, only: origin_actions
  resources :item_donation_records, only: origin_actions do
    resources :items, only: nested_actions
    member do
      get 'new_attachment'
      post 'attachments', to: 'item_donation_records#create_attachment', as: :attachments
      delete 'attachments/:attachment_id', to: 'item_donation_records#destroy_attachment', as: :attachment
    end
  end

  scope shallow_prefix: :donation_record do
    resources :donation_record do
      resources :actual_funds, controller: 'donation_record/actual_funds', shallow: true
      resources :interest_periods, controller: 'donation_record/interest_periods', shallow: true
    end
  end

  namespace :usage_record do
    resources :funds, only: [:show, :update, :edit]
  end
  resources :usage_records do
    resources :funds, controller: 'usage_record/funds', only: nested_actions
  end
  resources :individual_customers do
    resources :study_experiences, controller: 'schoolfellow/study_experiences'
    resources :teach_experiences, controller: 'schoolfellow/teach_experiences'
  end

  resources :fund_types

  resources :funds

  resources :project_types

  resources :project_states

  resources :project_levels

  resources :projects

  resources :customers do
    get 'edit_type', as: :edit_type
    post 'type_change', as: :type_change
    resources :contact_records
  end

  get 'common_customer/check_input', as: :common_customer_check_input, to: 'common_customers#check_input'

  resources :customer_groups do
    delete "customers/:id", to: 'customer_groups#delete_customer', as: :customer
    get "customers/:id", to: 'customer_groups#delete_customer'
  end
  resources :online_customers

  resources :corporate_customers do
    resources :link_men, controller: 'corporate_customers/link_men'
  end

  resources :individual_customers do
    resources :univ_experiences, controller: :schoolfellows
  end

  resources :customers

  namespace :employee do
    get 'manage', to: 'manage#index'
    get 'search', as: :search, to: 'manage#search'
    post 'search', as: :get_search, to: 'manage#result'
    namespace :manage do
      get 'projects'
      get 'customers'
      get 'funds', as: :funds
      namespace :fund do
        get 'manage_unit', as: :manage_unit
        get 'undetermined_fund', as: :undetermined_fund
      end
      get 'others'
    end
  end

  resources :employees

  devise_for :users, skip: [:registrations], controllers: { sessions: "users/sessions" } , path_names: { sign_in: 'login', sign_out: 'logout' }

  devise_scope :user do
    get "login", to: "users/sessions#new", as: :login
    delete "logout", to: "users/sessions#destroy", as: :logout
  end
  
  resources :users, only: [:show], :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ } #don't set this before devise, which will be confused between /:id <=> /sign_up

  root to: 'main#index'
  
  get 'main/index'

end

app/models/schoolfellow.rb
class Schoolfellow < ActiveRecord::Base
  belongs_to :individual_customer
  has_many :study_experiences
  has_many :teach_experiences
end

app/models/schoolfellow/study_experience.rb
class Schoolfellow::StudyExperience < ActiveRecord::Base
  belongs_to :schoolfellow
  belongs_to :major
  belongs_to :degree

  after_destroy :check_schoolfellow
  def check_schoolfellow
    if schoolfellow.study_experiences.empty? && 
      schoolfellow.teach_experiences.empty?
      schoolfellow.destroy
    end
  end
  def college
    major.univ_unit
  end
end

app/models/schoolfellow/teach_experience.rb
class Schoolfellow::TeachExperience < ActiveRecord::Base
  belongs_to :schoolfellow
  belongs_to :teacher_title
  belongs_to :univ_unit

  after_destroy :check_schoolfellow
  def check_schoolfellow
    if schoolfellow.study_experiences.empty? && 
      schoolfellow.teach_experiences.empty?
      schoolfellow.destroy
    end
  end
  def college
    univ_unit
  end
  def title
    teacher_title.name
  end
end

app/controllers/schoolfellow/study_experiences_controller.rb
class Schoolfellow::StudyExperiencesController < ApplicationController
  before_action :set_schoolfellow_study_experience, only: [:show, :edit, :update, :destroy]
  before_action :set_customer, only: [:new, :create, :edit, :update, :destroy]
  # GET /schoolfellow/study_experiences
  # GET /schoolfellow/study_experiences.json
  def index
    @schoolfellow_study_experiences = Schoolfellow::StudyExperience.all
  end

  # GET /schoolfellow/study_experiences/1
  # GET /schoolfellow/study_experiences/1.json
  def show
  end

  # GET /schoolfellow/study_experiences/new
  def new
    @schoolfellow_study_experience = Schoolfellow::StudyExperience.new
  end

  # GET /schoolfellow/study_experiences/1/edit
  def edit
  end

  # POST /schoolfellow/study_experiences
  # POST /schoolfellow/study_experiences.json
  def create
    unless @customer.schoolfellow
      @customer.schoolfellow = Schoolfellow.new
      @customer.save!
    end
    @schoolfellow_study_experience = Schoolfellow::StudyExperience.new(schoolfellow_study_experience_params)
    @schoolfellow_study_experience.schoolfellow = @customer.schoolfellow

    respond_to do |format|
      if @schoolfellow_study_experience.save
        format.html { redirect_to @customer, notice: 'Study experience was successfully created.' }
        format.json { render :show, status: :created, location: @schoolfellow_study_experience }
      else
        format.html { render :new }
        format.json { render json: @schoolfellow_study_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schoolfellow/study_experiences/1
  # PATCH/PUT /schoolfellow/study_experiences/1.json
  def update
    respond_to do |format|
      if @schoolfellow_study_experience.update(schoolfellow_study_experience_params)
        format.html { redirect_to @customer, notice: 'Study experience was successfully updated.' }
        format.json { render :show, status: :ok, location: @schoolfellow_study_experience }
      else
        format.html { render :edit }
        format.json { render json: @schoolfellow_study_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schoolfellow/study_experiences/1
  # DELETE /schoolfellow/study_experiences/1.json
  def destroy
    @schoolfellow_study_experience.destroy
    respond_to do |format|
      format.html { redirect_to @customer, notice: 'Study experience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schoolfellow_study_experience
      @schoolfellow_study_experience = Schoolfellow::StudyExperience.find(params[:id])
    end
    def set_customer
      @customer = IndividualCustomer.find(params[:individual_customer_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def schoolfellow_study_experience_params
      params.require(:schoolfellow_study_experience).permit(:major_id, :degree_id, 
        :attendance_date, :graduated_date, :student_number)
    end
end

app/controllers/schoolfellow/teach_experiences_controller.rb
class Schoolfellow::TeachExperiencesController < ApplicationController
  before_action :set_schoolfellow_teach_experience, only: [:show, :edit, :update, :destroy]
  before_action :set_customer, only: [:new, :create, :edit, :update, :destroy]

  # GET /schoolfellow/teach_experiences
  # GET /schoolfellow/teach_experiences.json
  def index
    @schoolfellow_teach_experiences = Schoolfellow::TeachExperience.all
  end

  # GET /schoolfellow/teach_experiences/1
  # GET /schoolfellow/teach_experiences/1.json
  def show
  end

  # GET /schoolfellow/teach_experiences/new
  def new
    @schoolfellow_teach_experience = Schoolfellow::TeachExperience.new
  end

  # GET /schoolfellow/teach_experiences/1/edit
  def edit
  end

  # POST /schoolfellow/teach_experiences
  # POST /schoolfellow/teach_experiences.json
  def create
    unless @customer.schoolfellow
      @customer.schoolfellow = Schoolfellow.new
      @customer.save!
    end
    @schoolfellow_teach_experience = Schoolfellow::TeachExperience.new(schoolfellow_teach_experience_params)
    @schoolfellow_teach_experience.schoolfellow = @customer.schoolfellow


    respond_to do |format|
      if @schoolfellow_teach_experience.save
        format.html { redirect_to @customer, notice: 'Teach experience was successfully created.' }
        format.json { render :show, status: :created, location: @schoolfellow_teach_experience }
      else
        format.html { render :new }
        format.json { render json: @schoolfellow_teach_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schoolfellow/teach_experiences/1
  # PATCH/PUT /schoolfellow/teach_experiences/1.json
  def update
    respond_to do |format|
      if @schoolfellow_teach_experience.update(schoolfellow_teach_experience_params)
        format.html { redirect_to @customer, notice: 'Teach experience was successfully updated.' }
        format.json { render :show, status: :ok, location: @schoolfellow_teach_experience }
      else
        format.html { render :edit }
        format.json { render json: @schoolfellow_teach_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schoolfellow/teach_experiences/1
  # DELETE /schoolfellow/teach_experiences/1.json
  def destroy
    @schoolfellow_teach_experience.destroy
    respond_to do |format|
      format.html { redirect_to @customer, notice: 'Teach experience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schoolfellow_teach_experience
      @schoolfellow_teach_experience = Schoolfellow::TeachExperience.find(params[:id])
    end

    def set_customer
      @customer = IndividualCustomer.find(params[:individual_customer_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schoolfellow_teach_experience_params
      params.require(:schoolfellow_teach_experience).permit(:teacher_title_id, :univ_unit_id, :teach_start, :teach_end, :idnum)
    end
end

app/controllers/schoolfellows_controller.rb
class SchoolfellowsController < ApplicationController
  before_action :set_customer
  def new
    @univ_experience = UnivExperience.new
  end

  def create
    @schoolfellow =  @customer.schoolfellow || (
      @customer.schoolfellow = Schoolfellow.new
      @customer.save
      @customer.schoolfellow
    )
    # raise univ_experience_params.inspect
    @univ_experience = UnivExperience.new(univ_experience_params)
    @univ_experience.schoolfellow = @schoolfellow

    respond_to do |format|
      if  @univ_experience.save
        format.html { redirect_to @customer, notice: '' }
      else
        format.html { render action: 'new' }
        format.json { render json: @univ_experience.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @univ_experience = UnivExperience.find(params[:id])
    @univ_experience.destroy
    if @customer.schoolfellow.univ_experiences.empty?
      @customer.schoolfellow.destroy
    end
    redirect_to @customer
  end
  private
    def set_customer
      @customer = IndividualCustomer.find(params[:individual_customer_id])
    end
    def univ_experience_params
      params.require(:univ_experience).
        permit(:major_id, :degree_id, :univ_unit_id, 
          :attendance_date, :graduated_date, :student_number)
    end
end

app/helpers/schoolfellow/study_experiences_helper.rb
module Schoolfellow::StudyExperiencesHelper
end

app/helpers/schoolfellow/teach_experiences_helper.rb
module Schoolfellow::TeachExperiencesHelper
end

app/helpers/schoolfellows_helper.rb
module SchoolfellowsHelper
end

app/views/schoolfellow/study_experiences/_form.html.erb
<div class="common-form">
<%= form_for(@schoolfellow_study_experience, url: individual_customer_study_experiences_path(@customer)) do |f| %>
  <% if @schoolfellow_study_experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schoolfellow_study_experience.errors.count, "error") %> prohibited this schoolfellow_study_experience from being saved:</h2>

      <ul>
      <% @schoolfellow_study_experience.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :student_number %><br />
    <%= f.text_field :student_number %>
  </div>

  <div class="field">
    <%= f.label :attendance_date %><br />
    <%= f.date_select :attendance_date, start_year: Date.today.year - 80 %>
  </div>

  <div class="field">
    <%= f.label :graduated_date %><br />
    <%= f.date_select :graduated_date, start_year: Date.today.year - 80 %>
  </div>

  <div class="field">
    <%= f.label :degree %><br />
    <%= f.select(:degree_id, Degree.all.collect {|e| [ e.name, e.id ] }) %>
  </div>

  <div class="field">
    <%= f.label :major %><br />
    <%= f.select(:major_id, Major.all.collect {|e| [ e.name+"(#{e.univ_unit.name})", e.id ] }) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/schoolfellow/study_experiences/edit.html.erb
<h1>Editing schoolfellow_study_experience</h1>

<%= render 'form' %>

<%= link_to 'Show', @schoolfellow_study_experience %> |
<%= link_to 'Back', schoolfellow_study_experiences_path %>

app/views/schoolfellow/study_experiences/index.html.erb
<h1>Listing schoolfellow_study_experiences</h1>

<table>
  <thead>
    <tr>
      <th>Schoolfellow</th>
      <th>Major</th>
      <th>Degree</th>
      <th>Attendance date</th>
      <th>Graduated date</th>
      <th>Student number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schoolfellow_study_experiences.each do |schoolfellow_study_experience| %>
      <tr>
        <td><%= schoolfellow_study_experience.schoolfellow %></td>
        <td><%= schoolfellow_study_experience.major %></td>
        <td><%= schoolfellow_study_experience.degree %></td>
        <td><%= schoolfellow_study_experience.attendance_date %></td>
        <td><%= schoolfellow_study_experience.graduated_date %></td>
        <td><%= schoolfellow_study_experience.student_number %></td>
        <td><%= link_to 'Show', schoolfellow_study_experience %></td>
        <td><%= link_to 'Edit', edit_schoolfellow_study_experience_path(schoolfellow_study_experience) %></td>
        <td><%= link_to 'Destroy', schoolfellow_study_experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Study experience', new_schoolfellow_study_experience_path %>

app/views/schoolfellow/study_experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Schoolfellow:</strong>
  <%= @schoolfellow_study_experience.schoolfellow %>
</p>

<p>
  <strong>Major:</strong>
  <%= @schoolfellow_study_experience.major %>
</p>

<p>
  <strong>Degree:</strong>
  <%= @schoolfellow_study_experience.degree %>
</p>

<p>
  <strong>Attendance date:</strong>
  <%= @schoolfellow_study_experience.attendance_date %>
</p>

<p>
  <strong>Graduated date:</strong>
  <%= @schoolfellow_study_experience.graduated_date %>
</p>

<p>
  <strong>Student number:</strong>
  <%= @schoolfellow_study_experience.student_number %>
</p>

<%= link_to 'Edit', edit_schoolfellow_study_experience_path(@schoolfellow_study_experience) %> |
<%= link_to 'Back', schoolfellow_study_experiences_path %>