config/routes.rb
Rails.application.routes.draw do

  post 'wechat_donate/create'

  post 'wechat_donate/notify'

  get 'wechat_donate/form_list', as: 'wechat_form_list'

  resources :item_categories

  resources :undetermined_funds

  namespace :region do
    get 'country', as: :country
    get 'state', as: :state
    get 'city', as: :city
  end

  namespace :schoolfellow do
    resources :teach_experiences
  end

  resources :teacher_titles

  resources :majors

  resources :degrees

  get 'users/search'
  post 'users/search', to:'users#do_search', as: 'user_search'

  nested_actions = [:new, :create]
  origin_actions = [:show, :edit, :update, :destroy]

  resources :customer_groups

  resources :donation_types

  resources :univ_units

  resources :univ_unit_managers

  resources :usage_types

  resources :projects do
    resources :donation_records, only: nested_actions
    resources :item_donation_records, only: nested_actions
    resources :usage_records, only: nested_actions
    scope module: :project do
      resources :link_men
      resources :news, only: nested_actions
      resources :necessary_dates, only: nested_actions
    end
    member do
      get 'history', as: :history
      get 'new_attachment'
      post 'attachments', to: 'projects#create_attachment', as: :attachments
      delete 'attachments/:attachment_id', to: 'projects#destroy_attachment', as: :attachment
    end
  end

    
  namespace :project do
    resources :news, only: origin_actions
    resources :necessary_dates, only: origin_actions
  end

  get 'link_men/search'
  post 'link_men/search', to: 'link_men#search', as: 'link_man_search'
  
  get 'customers/search', to: 'customers#search', as: 'customer_search'
  post 'customers/search', to: 'customers#do_search'

  resources :usage_records, only: origin_actions do
    member do
      get 'new_attachment'
      post 'attachments', to: 'usage_records#create_attachment', as: :attachments
      delete 'attachments/:attachment_id', to: 'usage_records#destroy_attachment', as: :attachment
    end
  end

  resources :donation_records, only: origin_actions do
    member do
      get 'trans_undetermined_in', as: :trans_undetermined_in
      post 'trans_undetermined_in', to: 'donation_records#handle_undetermined_trans'
      get 'new_attachment'
      post 'attachments', to: 'donation_records#create_attachment', as: :attachments
      delete 'attachments/:attachment_id', to: 'donation_records#destroy_attachment', as: :attachment
    end
  end

  resources :items, only: origin_actions
  resources :item_donation_records, only: origin_actions do
    resources :items, only: nested_actions
    member do
      get 'new_attachment'
      post 'attachments', to: 'item_donation_records#create_attachment', as: :attachments
      delete 'attachments/:attachment_id', to: 'item_donation_records#destroy_attachment', as: :attachment
    end
  end

  scope shallow_prefix: :donation_record do
    resources :donation_record do
      resources :actual_funds, controller: 'donation_record/actual_funds', shallow: true
      resources :interest_periods, controller: 'donation_record/interest_periods', shallow: true
    end
  end

  namespace :usage_record do
    resources :funds, only: [:show, :update, :edit]
  end
  resources :usage_records do
    resources :funds, controller: 'usage_record/funds', only: nested_actions
  end
  resources :individual_customers do
    resources :study_experiences, controller: 'schoolfellow/study_experiences'
    resources :teach_experiences, controller: 'schoolfellow/teach_experiences'
  end

  resources :fund_types

  resources :funds

  resources :project_types

  resources :project_states

  resources :project_levels

  resources :projects

  resources :customers do
    get 'edit_type', as: :edit_type
    post 'type_change', as: :type_change
    resources :contact_records
  end

  get 'common_customer/check_input', as: :common_customer_check_input, to: 'common_customers#check_input'

  resources :customer_groups do
    delete "customers/:id", to: 'customer_groups#delete_customer', as: :customer
    get "customers/:id", to: 'customer_groups#delete_customer'
  end
  resources :online_customers

  resources :corporate_customers do
    resources :link_men, controller: 'corporate_customers/link_men'
  end

  resources :individual_customers do
    resources :univ_experiences, controller: :schoolfellows
  end

  resources :customers

  namespace :employee do
    get 'manage', to: 'manage#index'
    get 'search', as: :search, to: 'manage#search'
    post 'search', as: :get_search, to: 'manage#result'
    namespace :manage do
      get 'projects'
      get 'customers'
      get 'funds', as: :funds
      namespace :fund do
        get 'manage_unit', as: :manage_unit
        get 'undetermined_fund', as: :undetermined_fund
      end
      get 'others'
    end
  end

  resources :employees

  devise_for :users, skip: [:registrations], controllers: { sessions: "users/sessions" } , path_names: { sign_in: 'login', sign_out: 'logout' }

  devise_scope :user do
    get "login", to: "users/sessions#new", as: :login
    delete "logout", to: "users/sessions#destroy", as: :logout
  end
  
  resources :users, only: [:show], :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ } #don't set this before devise, which will be confused between /:id <=> /sign_up

  root to: 'main#index'
  
  get 'main/index'

end

app/models/project/necessary_date.rb
class Project::NecessaryDate < ActiveRecord::Base
  belongs_to :project
end

app/models/project/news.rb
class Project::News < ActiveRecord::Base
  belongs_to :project
  validates_presence_of :title
  validates_presence_of :link
end

app/models/project_type.rb
class ProjectType < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/project/link_men_controller.rb
class Project::LinkMenController < ApplicationController
  before_action :set_project, except: [:search]
  before_action :set_link_man, only: [:show, :destroy]
  def show

  end

  def new
    @customers = IndividualCustomer.all
  end

  def create
    # raise params.inspect
    customers = params[:customer] || []
    customers.each do |c_id|
      customer = IndividualCustomer.find(c_id).customer
      begin
        @project.link_men<<customer
      rescue
        next
      end
    end
    redirect_to @project
  end

  def edit
  end

  def destroy
    @project.link_men.delete(@link_man.customer)
    redirect_to @project
  end

  def search
    search_name = params[:search]
    # raise params[:search].inspect
    # project = Project.find(params[:project_id])
    unless search_name
      @customers = IndividualCustomer.all
    else
      @customers = Customer.where(
        "name LIKE ? AND customer_type = ?", "%#{search_name}%", IndividualCustomer.to_s).collect{ |c| c.customer }
    end
    respond_to do |format|
      format.js
    end
  end

  private
    def set_project
      @project = Project.find(params[:project_id])
    end
    
    def set_link_man
      @link_man  = Customer.find(params[:id]).customer
    end
end

app/controllers/project/necessary_dates_controller.rb
class Project::NecessaryDatesController < ApplicationController
  before_action :set_project_necessary_date, only: [:show, :edit, :update, :destroy]
  before_action :set_project, only: [:create, :new, :edit, :destroy]

  # GET /project/necessary_dates
  # GET /project/necessary_dates.json
  def index
    @project_necessary_dates = Project::NecessaryDate.all
  end

  # GET /project/necessary_dates/1
  # GET /project/necessary_dates/1.json
  def show
  end

  # GET /project/necessary_dates/new
  def new
    @project_necessary_date = Project::NecessaryDate.new
    @project_necessary_date.project = @project
  end

  # GET /project/necessary_dates/1/edit
  def edit
  end

  # POST /project/necessary_dates
  # POST /project/necessary_dates.json
  def create
    @project_necessary_date = Project::NecessaryDate.new(project_necessary_date_params)
    @project_necessary_date.date = @project_necessary_date.date.change(year: 1900)

    respond_to do |format|
      if @project_necessary_date.save
        format.html { redirect_to @project }
        format.json { render :show, status: :created, location: @project_necessary_date }
      else
        format.html { render :new }
        format.json { render json: @project_necessary_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project/necessary_dates/1
  # PATCH/PUT /project/necessary_dates/1.json
  def update
    respond_to do |format|
      if @project_necessary_date.update(project_necessary_date_params)
        format.html { redirect_to @project_necessary_date }
        format.json { render :show, status: :ok, location: @project_necessary_date }
      else
        format.html { render :edit }
        format.json { render json: @project_necessary_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project/necessary_dates/1
  # DELETE /project/necessary_dates/1.json
  def destroy
    @project_necessary_date.destroy
    respond_to do |format|
      format.html { redirect_to @project }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_necessary_date
      @project_necessary_date = Project::NecessaryDate.find(params[:id])
    end

    def set_project
      @project = (@project_necessary_date && @project_necessary_date.project) || Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_necessary_date_params
      params.require(:project_necessary_date).permit(:date, :comment, :project_id)
    end
end

app/controllers/project/news_controller.rb
class Project::NewsController < ApplicationController
  before_action :set_project_news, only: [:show, :edit, :update, :destroy]
  before_action :set_project, only: [:create, :new, :edit, :destroy]
  # GET /project/news
  # GET /project/news.json
  def index
    @project_news = Project::News.all
  end

  # GET /project/news/1
  # GET /project/news/1.json
  def show
  end

  # GET /project/news/new
  def new
    @project_news = Project::News.new
  end

  # GET /project/news/1/edit
  def edit
  end

  # POST /project/news
  # POST /project/news.json
  def create
    @project_news = Project::News.new(project_news_params)

    respond_to do |format|
      if @project_news.save
        format.html { redirect_to @project }
        format.json { render :show, status: :created, location: @project_news }
      else
        format.html { render :new }
        format.json { render json: @project_news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project/news/1
  # PATCH/PUT /project/news/1.json
  def update
    respond_to do |format|
      if @project_news.update(project_news_params)
        format.html { redirect_to @project_news.project }
        format.json { render :show, status: :ok, location: @project_news }
      else
        format.html { render :edit }
        format.json { render json: @project_news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project/news/1
  # DELETE /project/news/1.json
  def destroy
    @project_news.destroy
    respond_to do |format|
      format.html { redirect_to @project }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_news
      @project_news = Project::News.find(params[:id])
    end

    def set_project
      @project = (@project_news && @project_news.project) || Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_news_params
      params.require(:project_news).permit(:title, :link, :comment).tap{ |p|
        p[:project_id] = @project.id
      }
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, 
    :new_attachment, :create_attachment, :destroy_attachment, :history]
  before_action :set_attachments, only: [:show]
  before_action :set_statistics_info, only: [:show]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @donation_records = @project.donation_records.with_fund.order("funds.time")
    @usage_records = @project.usage_records.with_amount.order("record_time")
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    if !user_can
      render 'cant_edit'
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.creator = current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    respond_to do |format|
      if user_can
        @project.destroy
        format.html { redirect_to employee_manage_projects_path }
        format.json { head :no_content }
      else
        format.html { render 'cant_edit' }
      end
    end
  end

  def new_attachment
    @attachment = Attachment.new
  end

  def create_attachment
    @attachment = Attachment.create(attachment_params)
    redirect_to @project
  end

  def destroy_attachment
    @attachment = Attachment.find(params[:attachment_id])
    raise 'unmatched project' if @project != @attachment.owner
    @attachment.destroy
    redirect_to @project
  end

  def history
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def user_can
      #@project.creator == current_user
      true
    end

    def set_attachments
      @attachments = @project.attachments
    end

    def set_statistics_info
      @all_plan_amount = @project.total_amount
      @all_actual_amount = @project.actual_amount
      @all_interest_amount = @project.interest_amount

      @principle_used_amount = @project.principle_used
      @interest_used_amount = @project.interest_used

      @all_principle_rest = @all_plan_amount - @principle_used_amount
      @actual_principle_rest = @all_actual_amount - @principle_used_amount
      @intereset_rest = @all_interest_amount - @interest_used_amount
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :serialnum, :create_date, :funder, :brief, :interest_rate,
        :gross, :balance, :endowment, :project_level_id, :project_state_id, :project_type_id, :comment,
        :create_unit_id, :create_manager_id)
    end
    def attachment_params
      params.require(:attachment).permit(:file).tap{ |p| p[:attachment_owner]=@project }
    end
end

app/helpers/project/necessary_dates_helper.rb
module Project::NecessaryDatesHelper
end

app/helpers/project/news_helper.rb
module Project::NewsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def show_manager
    link_to @project.create_manager.name, @project.create_manager if @project.create_manager
  end
end

app/views/projects/cant_edit.html.erb
您不是本项目的创建者，暂时不能改动此项目。

app/views/projects/edit.html.erb
<%= content_for :nav_bar_title do %>
    编辑项目
<% end %>

<%= content_for :nav_bar_function_area do %>
  <% if current_user.user_type == :Eemployee.to_s %>
    <%= link_to '返回', project_path(@project.id) %>
  <% end %>
<% end %>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1>项目列表</h1>
<%= link_to '新项目', new_project_path %> | 
<%= link_to '级别管理', project_levels_path %>
<%= link_to '状态管理', project_states_path %>
<%= link_to '类型管理', project_types_path %>

<table>
  <thead>
    <tr>
      <th>名称</th>
      <th>序列号</th>
      <th>创建日期</th>
      <th>创建者</th>
      <th>简介</th>
      <th>总额</th>
      <th>余额</th>
      <th>留本</th>
      <th>项目级别</th>
      <th>项目状态</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.serialnum %></td>
        <td><%= project.create_date %></td>
        <td><%= project.employee.name %></td>
        <td><%= get_brief_text project.brief, 24 %></td>
        <td><%= project.gross %></td>
        <td><%= project.balance %></td>
        <td><%= project.endowment.ch %></td>
        <td><%= project.project_level %></td>
        <td><%= project.project_state %></td>
        <td><%= link_to '显示', project %></td>
        <td><%= link_to '编辑', edit_project_path(project) %></td>
        <td><%= link_to '删除', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/projects/new.html.erb
<%= content_for :nav_bar_title do %>
    新建项目
<% end %>


<%= content_for :nav_bar_function_area do %>
  <% if session[:user_type] == :employee %>
    <%= link_to '返回', employee_manage_project_path %>
  <% end %>
<% end %>


<%= render 'form' %>

app/views/projects/new_attachment.html.erb
<%= form_for @attachment, :url => attachments_project_path, :html => { :multipart => true } do |f| %>
  <%= f.file_field :file%>
  <%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<%= content_for :nav_bar_function_area do %>
  <% if current_user.user_type == :Employee.to_s %>
    <%= link_to '编辑', edit_project_path(@project) %> |
    <%= link_to '返回', employee_manage_projects_path %>
  <% end %>
<% end %>

<%= content_for :nav_bar_title do %>
    项目信息
<% end %>

<!-- <div id="project-info-header"></div> -->
<div id="project-info">
  <table class="project-table">
    <tbody>
      <tr>
        <th>名称</th>
        <th>类型</th>
        <th>基金级别</th>
        <th>管理单位</th>
        <th>是否留本</th>
        <th>总额</th>
        <th>余额</th>
        <th>状态</th>
      </tr>
      <tr>
        <td><%= @project.name %></td>
        <td><%= @project.project_type.name %></td>
        <td><%= @project.project_level.name %></td>
        <td><%= @project.create_unit.name %></td>
        <td><%= @project.endowment_t %><%= "(#{@project.interest_rate}%)" if @project.endowment %></td>
        <td class="currency-show"><%= money_show @project.total_amount %></td>
        <td class="currency-show"><%= money_show @project.principle_rest %></td>
        <td><%= @project.project_state.name %></td>
      </tr>
    </tbody>
  </table>
  <div id="project-info-header">项目信息  <span><small><%= link_to '操作历史', history_project_path(@project), onp %></small></span></div>
  <div class="info-block">
    <p>
      <div><strong>名称：</strong> <span><%= @project.name %></span></div>
      <div><strong>编号：</strong> <span><%= @project.serialnum %></span></div>
      <div><strong>基金类型：</strong> <span><%= @project.project_type.name %></span></div>
      <% if on_admin %>
        <div><strong>录入人：</strong> <span><%= @project.creator.name %></span></div>
      <% end %>
    </p>
    <p>
      <div><strong>基金级别：</strong> <span><%= @project.project_level.name %></span></div>
      <div><strong>是否留本：</strong> <span><%= @project.endowment_t %></span></div>
    </p>
    <p>
      <div><strong>创建日期：</strong> <span><%= @project.create_date %></span></div>
    </p>

    <p>
      重要日期
      <%= link_to new_project_necessary_date_path(@project.id) do %>
        <%= button_tag '添加' %>
      <% end %>
    </p>
    <ul>
      <% @project.necessary_dates.each do |nd| %>
      <li>
        <%= nd.date.strftime("%m-%d") %>   <%= nd.comment %> 
        <span class='delete-cross'><%= link_to 'x', nd, method: :delete, data: { confirm: t('helpers.link.delete.confirm') } %></span>
      </li>
      <% end %>
    </ul>
  </div>
  <% if @project.endowment %>
  <div class="info-block">
    <strong>利率：</strong>
    <div><%= @project.interest_rate %>%</div>
  </div>
  <% end %>
  <hr>
  <div class="info-block">
    <p>
      <div><strong>管理单位：</strong> <span><%= link_to_with @project.create_unit, :name %></span></div>
      <div><strong>筹款专员：</strong> <span><%= show_manager %></span></div>
    </p>
    <p>
      <div><strong>电话：</strong> <span><%= @project.create_manager.tel if @project.create_manager%></span></div>
      <div><strong>邮箱：</strong> <span><%= @project.create_manager.email if @project.create_manager%></span></div>
      <div><strong>传真：</strong> <span><%= @project.create_manager.fax if @project.create_manager%></span></div>
      <div><strong>邮编：</strong> <span><%= @project.create_manager.postcode if @project.create_manager%></span></div>
    </p>
  </div>
  <hr>
  <div class="info-block">
    <p>
      <div><strong>联系人：</strong> 
        <% @project.link_men.each do |lm| %>
          <span><%= link_to lm.name, project_link_man_path(@project.id, lm.id) %></span>
        <% end %>
        <%= link_to new_project_link_man_path(@project.id) do %>
          <%= button_tag '添加' %>
        <% end %>
      </div>
    </p>
  </div>
  <hr>
  <div class="info-block">
    <p>
      <div><strong>概要：</strong> <span><%= simple_format @project.brief %></span></div>
    </p>
    <p>
      <div><strong>备注：</strong> <span><%= simple_format @project.comment %></span></div>
    </p>
    <p>

      <div><strong>附件：</strong>
        <% @attachments.each do |a| %>
        <p><%= link_to a.filename, a.file.url %><span class='delete-attachment'><%= link_to t('helpers.link.delete.name'),attachment_project_path(@project, a), method: :delete, data: { confirm: t('helpers.link.delete.confirm') } %></span></p>
        <% end %>
        <div>
          <%= link_to new_attachment_project_path, onp do %>
            <%= button_tag '添加' %>
          <% end %>
        </div>
      </div>
    </p>
  </div>
  <hr>
  <div id='project-news' class="info-block">
    <strong>新闻报道</strong>
    <div id='project-news-list'>
      <% @project.news.each_with_index do |n, i| %>
        <p><%= "#{i+1}." %><span><span class="title"><%= link_to n.title, n.link, onp %></span><span class='function-link'><%= ' '*16 %><%= link_to '编辑', edit_project_news_path(n) %>|<%= link_to '删除', n, del_confirm %></span></span> </p>
      <% end %>
    </div>
    <br>
    <%= link_to new_project_news_path(@project) do %>
      <%= button_tag '添加' %>
    <% end %>
  </div>


  <hr>
</div>

<% endowment = @project.endowment %>

<div><b>捐赠记录</b> <%= link_to '添加资金捐赠', new_project_donation_record_path(@project) %> | <%= link_to '添加物品捐赠', new_project_item_donation_record_path(@project) %></div>
  <div class="project-table-header">
    <!-- <span>计划到账： <%= money_show @all_plan_amount %></span> -->
    <span>已到账总额：<%= money_show @all_actual_amount %></span>
    <% if endowment %>
    <span>利息：<%= money_show @all_interest_amount %></span>
    <% end %>
  </div>
  <table class="project-table">
    <tbody>
      <tr>
        <th>序号 </th>
        <!-- <th>编号</th> -->
        <th>类型</th>
        <th>捐赠人</th>
        <th>币种</th>
        <th>日期</th>
        <!-- <th>计划到账</th> -->
        <th>实际到账</th>
        <% if endowment %>
        <th>利息收入</th>
        <% end %>
        <th>备注</th>
        <th>其他</th>
      </tr>

    <% @donation_records.each_with_index do |r, index| %>
              <tr>
        <td><%= index+1 %></td>
        <!-- <td></td> -->
        <td><%= r.donation_type.name if r.donation_type %></td>
        <td><%= link_to_with r.customer, :name %></td>
        <td><%= Currency.find(r.currency_id).name %></td>
        <td><%= localize_date r.time.to_time %></td>
        <!-- <td class="currency-show"><%# money_show r.amount %></td> -->
        <td class="currency-show"><%= money_show r.actual_amount %></td>
        <% if endowment %>
        <td class="currency-show"><%= money_show r.interest_amount %></td>
        <% end %>
        <td><%= truncate r.comment, length: 12 %></td>
        <td><%= link_to "详情", r %>|<%= link_to "编辑", edit_donation_record_path(r) %>|<%= link_to '删除', r, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

    <% end %>

    </tbody>
  </table>
  <div class="project-table-header">
    <span>物品捐赠</span>
  </div>
  <table class="project-table">
    <tbody>
      <tr>
        <th>序号 </th>
        <th>捐赠人</th>
        <th>日期</th>
        <th>价值</th>
        <th>其他</th>
      </tr>

      <% @project.item_donation_records.order(:time).each_with_index do |r, index| %>
      <tr>
        <td><%= index+1 %></td>
        <td><%= link_to_with r.customer, :name %></td>
        <td><%= l_d r.time %></td>
        <td><%= money_show r.total_price %></td>
        <td><%= link_to "详情", r %>|<%= link_to "编辑", edit_item_donation_record_path(r) %>|<%= link_to '删除', r, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <p></p>

<div><b>使用记录</b> <%= link_to '添加', new_project_usage_record_path(@project) %></div>
  <div class="project-table-header">
  <% if endowment %>
    <span>本金支出：<%= money_show @principle_used_amount %></span>
    <span>利息支出 <%= money_show @interest_used_amount %></span>
    <span>本金余额：<%= money_show @actual_principle_rest %> </span>
    <span>利息余额： <%= money_show @intereset_rest %></span>
  <% else %>
  总支出：<%= money_show @principle_used_amount %> 余额：<%= money_show @actual_principle_rest %>
  <% end %>
  </div>
  <table class="project-table">
    <tbody>
      <tr>
        <th>序号 </th>
        <th>日期</th>
        <th>执行单位</th>
        <th>批准人</th>        
        <th>受益单位</th>
        <th>经办人</th>
        <th>使用本金</th>
        <% if endowment %>
        <th>使用利息</th>
        <% end %>
        <th>用途</th>
        <th>备注</th>
        <th>其他</th>
      </tr>
      <% @usage_records.each_with_index do |r, index| %>
      <tr>
        <td><%= index+1 %></td>
        <td><%= l_d r.time %></td>
        <td><%= link_to_with r.exec_unit, :name %></td>
        <td><%= link_to_with r.exec_manager, :name %></td>        
        <td><%= link_to_with r.benefit_unit, :name %></td>
        <td><%= link_to_with r.benefit_manager, :name %></td>
        <td class="currency-show"><%= money_show r["principle_amount"]%></td>
        <% if endowment %>
        <td class="currency-show"><%= money_show r["interest_amount"]%></td>
        <% end %>
        <td><%= (rt = r.usage_type).nil? ? @project.project_type.name : rt.name%></td>
        <td><%= r.comment %></td>
        <td><%= link_to '查看', r %>|<%= link_to '编辑', edit_usage_record_path(r) %><%= link_to '删除', r, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

<% if on_admin %>
  <%= link_to '删除项目', project_path(@project), method: :delete, data: { confirm: t('helpers.link.delete.confirm') } %>
<% end %>