config/routes.rb
Rails.application.routes.draw do

  post 'wechat_donate/create'

  post 'wechat_donate/notify'

  get 'wechat_donate/form_list', as: 'wechat_form_list'

  resources :item_categories

  resources :undetermined_funds

  namespace :region do
    get 'country', as: :country
    get 'state', as: :state
    get 'city', as: :city
  end

  namespace :schoolfellow do
    resources :teach_experiences
  end

  resources :teacher_titles

  resources :majors

  resources :degrees

  get 'users/search'
  post 'users/search', to:'users#do_search', as: 'user_search'

  nested_actions = [:new, :create]
  origin_actions = [:show, :edit, :update, :destroy]

  resources :customer_groups

  resources :donation_types

  resources :univ_units

  resources :univ_unit_managers

  resources :usage_types

  resources :projects do
    resources :donation_records, only: nested_actions
    resources :item_donation_records, only: nested_actions
    resources :usage_records, only: nested_actions
    scope module: :project do
      resources :link_men
      resources :news, only: nested_actions
      resources :necessary_dates, only: nested_actions
    end
    member do
      get 'history', as: :history
      get 'new_attachment'
      post 'attachments', to: 'projects#create_attachment', as: :attachments
      delete 'attachments/:attachment_id', to: 'projects#destroy_attachment', as: :attachment
    end
  end

    
  namespace :project do
    resources :news, only: origin_actions
    resources :necessary_dates, only: origin_actions
  end

  get 'link_men/search'
  post 'link_men/search', to: 'link_men#search', as: 'link_man_search'
  
  get 'customers/search', to: 'customers#search', as: 'customer_search'
  post 'customers/search', to: 'customers#do_search'

  resources :usage_records, only: origin_actions do
    member do
      get 'new_attachment'
      post 'attachments', to: 'usage_records#create_attachment', as: :attachments
      delete 'attachments/:attachment_id', to: 'usage_records#destroy_attachment', as: :attachment
    end
  end

  resources :donation_records, only: origin_actions do
    member do
      get 'trans_undetermined_in', as: :trans_undetermined_in
      post 'trans_undetermined_in', to: 'donation_records#handle_undetermined_trans'
      get 'new_attachment'
      post 'attachments', to: 'donation_records#create_attachment', as: :attachments
      delete 'attachments/:attachment_id', to: 'donation_records#destroy_attachment', as: :attachment
    end
  end

  resources :items, only: origin_actions
  resources :item_donation_records, only: origin_actions do
    resources :items, only: nested_actions
    member do
      get 'new_attachment'
      post 'attachments', to: 'item_donation_records#create_attachment', as: :attachments
      delete 'attachments/:attachment_id', to: 'item_donation_records#destroy_attachment', as: :attachment
    end
  end

  scope shallow_prefix: :donation_record do
    resources :donation_record do
      resources :actual_funds, controller: 'donation_record/actual_funds', shallow: true
      resources :interest_periods, controller: 'donation_record/interest_periods', shallow: true
    end
  end

  namespace :usage_record do
    resources :funds, only: [:show, :update, :edit]
  end
  resources :usage_records do
    resources :funds, controller: 'usage_record/funds', only: nested_actions
  end
  resources :individual_customers do
    resources :study_experiences, controller: 'schoolfellow/study_experiences'
    resources :teach_experiences, controller: 'schoolfellow/teach_experiences'
  end

  resources :fund_types

  resources :funds

  resources :project_types

  resources :project_states

  resources :project_levels

  resources :projects

  resources :customers do
    get 'edit_type', as: :edit_type
    post 'type_change', as: :type_change
    resources :contact_records
  end

  get 'common_customer/check_input', as: :common_customer_check_input, to: 'common_customers#check_input'

  resources :customer_groups do
    delete "customers/:id", to: 'customer_groups#delete_customer', as: :customer
    get "customers/:id", to: 'customer_groups#delete_customer'
  end
  resources :online_customers

  resources :corporate_customers do
    resources :link_men, controller: 'corporate_customers/link_men'
  end

  resources :individual_customers do
    resources :univ_experiences, controller: :schoolfellows
  end

  resources :customers

  namespace :employee do
    get 'manage', to: 'manage#index'
    get 'search', as: :search, to: 'manage#search'
    post 'search', as: :get_search, to: 'manage#result'
    namespace :manage do
      get 'projects'
      get 'customers'
      get 'funds', as: :funds
      namespace :fund do
        get 'manage_unit', as: :manage_unit
        get 'undetermined_fund', as: :undetermined_fund
      end
      get 'others'
    end
  end

  resources :employees

  devise_for :users, skip: [:registrations], controllers: { sessions: "users/sessions" } , path_names: { sign_in: 'login', sign_out: 'logout' }

  devise_scope :user do
    get "login", to: "users/sessions#new", as: :login
    delete "logout", to: "users/sessions#destroy", as: :logout
  end
  
  resources :users, only: [:show], :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ } #don't set this before devise, which will be confused between /:id <=> /sign_up

  root to: 'main#index'
  
  get 'main/index'

end

app/models/corporate_customer.rb
class CorporateCustomer < ActiveRecord::Base
  include CommonCustomer
  acts_as_common_customer

  has_many :link_men, dependent: :destroy
  # has_many :ordinary_link_men, ->{ where('corporate_customer_link_men.corporate_customer_link_man_link_type_id' => 
  #   CorporateCustomer::LinkMan::LinkType.find_by(name: :ordinary).id) },
  #   class_name: :IndividualCustomer, through: :link_men, source: :individual_customer
  # has_many :manager_link_men, ->{ where('corporate_customer_link_men.corporate_customer_link_man_link_type_id' => 
  #   CorporateCustomer::LinkMan::LinkType.find_by(name: :manager).id) },
  #   class_name: :IndividualCustomer, through: :link_men, source: :individual_customer
  
  [:ordinary, :manager].each do |prefix|
    define_method("#{prefix}_link_men") do
      link_men.where(corporate_customer_link_man_link_type_id: CorporateCustomer::LinkMan::LinkType.send("#{prefix}_id"))
    end
  end

  def self.all_spy
    all.sort_by{ |e| e.name_with_py! }
  end
end

app/models/corporate_customer/link_man.rb
class CorporateCustomer::LinkMan < ActiveRecord::Base
  belongs_to :corporate_customer
  belongs_to :individual_customer
  belongs_to :corporate_customer_link_man_link_type, class_name: 'CorporateCustomer::LinkMan::LinkType'

  alias_attribute :instance, :individual_customer
  alias_attribute :type, :corporate_customer_link_man_link_type
  
  validates_uniqueness_of :individual_customer,  scope: [:corporate_customer]
end

app/models/corporate_customer/link_man/link_type.rb
class CorporateCustomer::LinkMan::LinkType < ActiveRecord::Base
  
  all.each do |type|
    self.class.class_eval(%Q{
      def #{type.name}_id
        #{type.id}
      end
    })
  end

  def name_t
    return '联系人' if name=='ordinary'
    return '负责人' if name=='manager'
  end
end

app/controllers/corporate_customers/link_men_controller.rb
class CorporateCustomers::LinkMenController < ApplicationController
  before_action :set_customer, except: [:search]
  before_action :set_link_man, only: [:show, :destroy]
  def show

  end

  def new
    @customers = IndividualCustomer.all
  end

  def create
    linkmen = params[:customer] || []
    linkmen.each do |l_id|
      begin
        @customer.link_men<< CorporateCustomer::LinkMan.new( 
          individual_customer_id: l_id, corporate_customer_id: params[:corporate_customer_id], 
          corporate_customer_link_man_link_type_id: params[:type])
      rescue
        raise '123'
      end
    end
    redirect_to @customer
  end

  def edit
  end

  def destroy
    @customer.link_men.delete(@link_man)
    redirect_to @customer
  end

  def search
    search_name = params[:search]
    # raise params[:search].inspect
    # project = Project.find(params[:project_id])
    unless search_name
      @customers = IndividualCustomer.all
    else
      @customers = Customer.where(
        "name LIKE ? AND customer_type = ?", "%#{search_name}%", IndividualCustomer.to_s).collect{ |c| c.customer }
    end
    respond_to do |format|
      format.html
    end
  end

  private
    def set_customer
      @customer = CorporateCustomer.find(params[:corporate_customer_id])
    end
    
    def set_link_man
      @link_man  = CorporateCustomer::LinkMan.find(params[:id])
    end
end

app/controllers/corporate_customers_controller.rb
class CorporateCustomersController < CommonCustomersController
  private
end

app/helpers/corporate_customers_helper.rb
module CorporateCustomersHelper
end

app/views/corporate_customers/_form.html.erb
<div class="common-form">
<%= form_for(@self_customer) do |f| %>
  <% if @self_customer.errors.any? %>
    <div id="error_explanation">
      <%= error_messages_for @self_customer %>
    </div>
  <% end %>

  <%= f.fields_for :customer do |c_f| %>
    <%= render 'customers/form', {f: c_f, of: f} %>
  <% end %>

  <div class="actions">
    <%= f.submit '提交'%>
  </div>
<% end %>
</div>

app/views/corporate_customers/edit.html.erb
<%= render 'form' %>
<%= link_to '变更用户类型', customer_edit_type_path(@self_customer.customer) %>

app/views/corporate_customers/index.html.erb
<h1>Listing corporate_customers</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @self_customers.each do |corporate_customer| %>
      <tr>
        <td><%= corporate_customer.customer %></td>
        <td><%= link_to 'Show', corporate_customer %></td>
        <td><%= link_to 'Edit', edit_corporate_customer_path(corporate_customer) %></td>
        <td><%= link_to 'Destroy', corporate_customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Corporate customer', new_corporate_customer_path %>

app/views/corporate_customers/new.html.erb
<%= render 'corporate_customers/form' %>

app/views/corporate_customers/show.html.erb
<%= content_for :nav_bar_function_area do %>
  <% if current_user.user_type.downcase == :employee.to_s %>
    <%= link_to '编辑', edit_corporate_customer_path(@self_customer) %> |
    <%= link_to '返回', employee_manage_customers_path %>
    <% if current_user.account.to_s == 'fkadmin' %>
    |<%= link_to '删除', corporate_customer_path(@self_customer), method: :delete, data: { confirm: t('helpers.link.delete.confirm') } %>
    <% end %>
  <% end %>
<% end %>

<%= content_for :nav_bar_title do %>
    客户信息
<% end %>
<div class="info-show">
  <div class="info-block">
    <p>
      <div><strong><%= @self_customer.class.human_attribute_name :name %>：</strong> <span><%= @self_customer.name! %></span></div>
      <div><small>录入人： <span><%= link_to @self_customer.creator!.name, @self_customer.creator! %></span></small></div>
    </p>
  </div>
</div>
<div id="project-info">
  <%= render 'common_customers/info' %>

  <div class="info-block">
    <strong>负责人：</strong> 
    <% @self_customer.manager_link_men.each do |lm| %>
      <span><%= link_to lm.instance.name!, corporate_customer_link_man_path(@self_customer, lm.id) %></span>
    <% end %>
    <%= link_to new_corporate_customer_link_man_path(@self_customer, type: CorporateCustomer::LinkMan::LinkType.manager_id) do %>
      <%= button_tag '添加' %>
    <% end %>
  </div>
  <div class="info-block">
    <strong>联系人：</strong> 
    <% @self_customer.ordinary_link_men.each do |lm| %>
      <span><%= link_to lm.instance.name!, corporate_customer_link_man_path(@self_customer, lm.id) %></span>
    <% end %>
    <%= link_to new_corporate_customer_link_man_path(@self_customer, type: CorporateCustomer::LinkMan::LinkType.ordinary_id) do %>
      <%= button_tag '添加' %>
    <% end %>
  </div>
  <hr>

  <%= render 'common_customers/record' %>
</div>